//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAnalytics {
	
	
	public partial class Courses {
		
		protected System.Web.UI.HtmlControls.HtmlForm mainForm;
		
		protected System.Web.UI.WebControls.Label lblTitle;
		
		protected System.Web.UI.WebControls.HiddenField valCourse;
	}
}
