//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAnalytics {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm mainForm;
		
		protected System.Web.UI.WebControls.HiddenField valSearch;
		
		protected System.Web.UI.WebControls.TextBox txtSearch;
		
		protected System.Web.UI.WebControls.Button btnSearch;
		
		protected System.Web.UI.WebControls.HyperLink linkPrev;
		
		protected System.Web.UI.WebControls.DropDownList listPages;
		
		protected System.Web.UI.WebControls.HyperLink linkNext;
		
		protected System.Web.UI.WebControls.Table tblCourses;
	}
}
