//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAnalytics {
	
	
	public partial class General {
		
		protected System.Web.UI.HtmlControls.HtmlForm mainForm;
		
		protected System.Web.UI.WebControls.DropDownList listSemesters;
		
		protected System.Web.UI.WebControls.HiddenField valEnrollments;
		
		protected System.Web.UI.WebControls.HiddenField valRecommends;
		
		protected System.Web.UI.WebControls.HiddenField valWorkloads;
		
		protected System.Web.UI.WebControls.HiddenField valEnrollRec;
		
		protected System.Web.UI.WebControls.HiddenField valWorkRec;
	}
}
